### ISSUE TITLE
Missing icon on title line

### ISSUE THREAD

**Issue by MTRNord** [martignoni/hugo-notice#1]
Hi this is awesome but it seems like the CSS for the Icon is missing. Any hints how to get it working?

**Comment by martignoni** [comment]
Please elaborate. The CSS is obviously here.

**Comment by MTRNord** [comment]
On my page it loads the notice fine except the Icon. Basicly the content of `.notice-title:before{content:'\f05a'}` which sets the icon doesn't seem to load any icon. Check: https://nordgedanken.gitlab.io/posts/2015-01-04-first-post/ for example.

![grafik](https://user-images.githubusercontent.com/1374914/57585305-bf29d280-74e6-11e9-970a-38bd11ab6e63.png)

**Comment by MTRNord** [comment]
If it makes a difference: I am using Windows 10 with Firefox 66.0.3 (64-Bit)

**Comment by martignoni** [comment]
It seems you don't have font-awesome available.

**Comment by MTRNord** [comment]
Is simply adding it to the layout enough to fix the issue?

**Comment by martignoni** [comment]
Yes.

**Comment by MTRNord** [comment]
Thanks! I will do that :)

**Comment by MTRNord** [comment]
Actually it seems like the Font Family name changed in the newest version:

```
font-family: "Font Awesome 5 Free";
```

Using that it starts to work.

(See https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements )

**Comment by martignoni** [comment]
But you can still use [Font Awesome 4](https://fontawesome.com/v4.7.0/). I personally use it.

**Comment by martignoni** [comment]
@MTRNord FYI: just updated. New version works with both older and current Font Awesome release. Thanks for the idea.

**Comment by MTRNord** [comment]
@martignoni thanks a lot for making that possible
