### ISSUE TITLE
Possibility for footnotes

### ISSUE THREAD

**Issue by hayribakici** [martignoni/hugo-notice#11]
Hi, 
thank you for this shortcode. 
I was wondering, if it is possible to add footnotes? Currently they are not rendered.

Thank you and cheers.

**Comment by martignoni** [comment]
You mean rendering a footnote within the notice or outside (at the end of the page)?

**Comment by hayribakici** [comment]
Thanks for the quick response.
I meant, having a footnote inside the notice that, in which the footnote text is at the end of the page.

Currently, the notice shortcode renders the `[^1]`, too.

**Comment by martignoni** [comment]
This is unfortunately not possible with Hugo without using workarounds.

[This forum discussion](https://discourse.gohugo.io/t/markdown-reference-links-in-shortcodes) explains why reference-style links do not work in shortcodes. As footnotes are special reference-style links, result is the same.

**Comment by hayribakici** [comment]
Thank you for the clarification.
