### ISSUE TITLE
Padding in first notice box

### ISSUE THREAD

**Issue by gary-tai** [martignoni/hugo-notice#12]
Repo: https://github.com/gary-tai/contour

There is top padding in the first notice box, but not the subsequent notices.
I have implemented the following:

- copied en.yaml to /themes/contour/i18n
- copied notice.html to  /themes/contour/layouts/shortcodes
- added shortcode to md page

Test with page: 
http://localhost:1313/docs/main/start-contributing/
![image](https://user-images.githubusercontent.com/85881851/129763596-da527fe0-736c-43b7-aa78-c4da0a6ddee3.png)

**Comment by martignoni** [comment]
This is a bug. Thanks for raising it.

**Comment by martignoni** [comment]
This should be fixed now. Please reopen if it's not the case.

**Comment by gary-tai** [comment]
Nicolas - thanks for the quick fix! Works great.
