### ISSUE TITLE
Background shading expands past the end of the notice text

### ISSUE THREAD

**Issue by georgew509** [martignoni/hugo-notice#18]
I wanted to start by saying that this short code is awesome, but I am seeing one minor issue. Not sure how to best describe this issue, but here's an image of what I am seeing:

<img width="943" alt="Screen Shot 2022-07-05 at 11 06 21 AM" src="https://user-images.githubusercontent.com/5678137/177370541-29146d06-096e-4181-a862-e33092ea36c9.png">

This is a single column display where the text is limited to about "70 characters". The note text and even the bright blue bar fit within that limit. But the light blue background expands to the boarder of the browser window. How can this be changed so that the bright blue bar and light blue background are aligned?

I am using the [Hugo Zen theme](https://github.com/frjo/hugo-theme-zen).

Thanks much.

**Comment by martignoni** [comment]
I cannot reproduce this behaviour. Can you please show us the code?

**Comment by georgew509** [comment]
Thanks for the reply. I have switched away from Hugo and no longer have access to the code.
