### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by MarekPikula** [martignoni/hugo-notice#19]
I would like to use this module with a theme which natively supports dark mode (namely [Stack](https://github.com/CaiJimmy/hugo-theme-stack)). Unfortunately, as I can see, it doesn't change the colours when the dark mode is enabled.

This is how it looks like with the base theme in dark mode:
![obraz](https://user-images.githubusercontent.com/1504981/183265203-18163150-b743-4f80-80e4-cad03bf4fd84.png)

It's not terrible, but it would be nice if the colour scheme changed. Do you think it's easy to implement, or should I request it in the theme itself?

**Comment by callaloo** [comment]
Try the `body.dark` CSS [here](https://github.com/martignoni/hugo-notice/pull/16).

**Comment by martignoni** [comment]
This is fixed by PR #16 and commit 029d66f. Enjoy!

**Comment by sourcevault** [comment]
How do you change to dark mode colors ?

**Comment by martignoni** [comment]
There: https://github.com/martignoni/hugo-notice/blob/cce7afd430d49fe01ad6e2c006c3518fddc8ad77/layouts/shortcodes/notice.html#L8

**Comment by martignoni** [comment]
> How do you change to dark mode colors ?

Re-reading this, I'm thinking your asking how to enable dark mode in your website (sorry for the misunderstanding).

Make your CSS use `prefers-color-scheme` and it'll work automatically. Another way to make it work is to inject class `dark` to the body of your page when dark mode is needed.

**Comment by oliverlabs** [comment]
Hi @martignoni , thanks so much for clarifying this. It helped :)

**Comment by martignoni** [comment]
> Please consider adding it to the official documentation

I thought the same thing after reading you issue and this one, and began already. Thanks for the feedback and idea.

**Comment by martignoni** [comment]
Done: ca7c13c0f8c32d1b83529bfd7d0d10aa9314a1c2.
