### ISSUE TITLE
Large blank space before the first notice when viewing with macOS Safari

### ISSUE THREAD

**Issue by georgew509** [martignoni/hugo-notice#25]
(After trying a different CMS, I have moved back to Hugo, the Hugo Zen theme, and the Hugo-notice theme component.)

The Hugo Notices really look great, but when viewing a post in macOS Safari, I have noticed that there are a number of blank lines present before the first notice. For example (from [Configure Apache and PHP-FPM on macOS](https://altoplace.com/macos/configure-apache-and-php-fpm-on-macos/)):

<img width="747" alt="Screen Shot 2022-10-11 at 3 11 01 PM" src="https://user-images.githubusercontent.com/5678137/195188965-01f70561-c648-4cb1-b55a-2714da1e13a8.png">

This only happens for the first notice in a post and it only happens in macOS Safari. I don't see the issue in Google Chrome. There are several more "Notes" in this post, and they all look fine (not a bunch of blank lines before the Note).

I understand that the first "notice" loads some CSS code, so I was wondering if that's related. Is this just a bug in Safari, and are there any known workarounds?

Thanks,
George

**Comment by martignoni** [comment]
Can't reproduce, please show an example.

**Comment by martignoni** [comment]
I cannot see the problem on https://altoplace.com/macos/configure-apache-and-php-fpm-on-macos/. 

I think there's a problem in your website, since I cannot see the notice's icons and all the notices in this article are of type "Note".

**Comment by georgew509** [comment]
I think that it was an issue with my website. Thanks for looking and sorry for the trouble.
