### ISSUE TITLE
Non-preset noticeType has wrong color in dark mode

### ISSUE THREAD

**Issue by rea1shane** [martignoni/hugo-notice#39]
Light mode:

<img width="823" alt="image" src="https://github.com/martignoni/hugo-notice/assets/93363751/29776154-fde8-49c4-9bc2-c131c24906e4">

Dark mode:

<img width="784" alt="image" src="https://github.com/martignoni/hugo-notice/assets/93363751/6a7ab57c-40ac-445f-b81f-3ff03f33a0cb">

Souece code:

```
{{< notice Others >}}
Non-default type.
{{< /notice >}}
```

**Comment by martignoni** [comment]
Fixed, closing.
