### ISSUE TITLE
No space between a code block and a notice block

### ISSUE THREAD

**Issue by kamasylvia** [martignoni/hugo-notice#44]
## No space between a code block and a notice block
Example markdown code

![图片](https://github.com/user-attachments/assets/3b52678e-5941-471d-afc0-e27830ab362d)

Output
![图片](https://github.com/user-attachments/assets/0c1e4d95-b9e2-4af5-bea4-243cfd2a6d89)

## Notice followed by a paragraph
Example markdown code
```md
A paragraph

{{< notice warning >}}
This is a notice WARNING!
{{< /notice >}}
```

Output

![图片](https://github.com/user-attachments/assets/72264bf0-f237-44cb-ba57-304038158268)

## Expected behavior
There should be a space between code block and the notice block.

**Comment by kamasylvia** [comment]
> Can you explain what's the problem: I'm seeing a space between the text and the notice in both of the screenshots.

No space between the code block and the notice block as the first image show.

![图片](https://github.com/user-attachments/assets/2d4cd6f6-6bf7-4394-8633-0a1bfc28479e)

**Comment by martignoni** [comment]
Cannot reproduce, see screenshot. Seems to be a problem with you theme: the notice block is centered, which it should not.

<img width="563" alt="code-and-notice" src="https://github.com/user-attachments/assets/905fc285-54e2-4b3e-aaeb-6f61cc79517a">

**Comment by kamasylvia** [comment]
Thank you for your response. Since this is a matter of theme compatibility, I've decided to close this issue.
