### ISSUE TITLE
Unexpected rendering

### ISSUE THREAD

**Issue by teopost** [martignoni/hugo-notice#8]
I added the hugo-notice component to my website, but the visualization look unexpected with a very wide frame

You can see the result here:
* https://www.stefanoteodorani.it/sandbox0/

**Comment by martignoni** [comment]
The only problem I'm seeing is the margin (and maybe the line height) of the `p`, since you've this in your CSS
```

.article-entry p, .article-entry table {
    line-height: 1.6em;
    margin: 1.6em 0;
}
```
Fix your CSS.
